//using CodingProblems_GoogleClassRoom.PracticeProblem1;
//new Add2Numbers().addition(10, 20);
//new Area_of_a_circle().Area_of_circle(10);
//new Volume_of_a_Cylinder().Volume_of_Cylinder(10, 20);
//new Convert_Kilometers_to_Miles().KmToMiles();
//new Perimeter_of_a_Rectangle().Perimeter_of_Rectangle(10, 20);
//new Power_Calculation().Power_Calculation(2, 3);
//new Volume_of_a_Cylinder().Volume_of_Cylinder(10, 20);

//using CodingProblems_GoogleClassRoom.PracticeProblem2;
//Problem1_HarryAge.Run();
//Problem2_SamAveragePCM.Run();
//Problem3_KmToMiles.Run();
//Problem4_ProfitLoss.Run();
//Problem5_PensDivision.Run();
//Problem6_UniversityDiscount.Run();
//Problem7_VolumeOfEarth.Run();
//Problem8_KmToMiles_Input.Run();
//Problem9_DiscountWithInput.Run();
//Problem10_HeightCmToFeetInches.Run();
//Problem11_BasicCalculator.Run();
//Problem12_AreaOfTriangle.Run();
//Problem13_SideFromPerimeter.Run();
//Problem14_FeetToYardsMiles.Run();
//Problem15_TotalPurchasePrice.Run();
//Problem16_MaxHandshakes.Run();

//using CodingProblems_GoogleClassRoom.PracticeProblem3;
//Problem1_DisplayResult.Run();
//Problem2_EricTravels.Run();
//Problem3_QuotientRemainder.Run();
//Problem4_IntOperations.Run();
//Problem5_DoubleOperations.Run();
//Problem6_CelsiusToFahrenheit.Run();
//Problem7_FahrenheitToCelsius.Run();
//Problem8_TotalIncome.Run();
//Problem9_SwapNumbers.Run();
//Problem10_TravelInput.Run();
//Problem11_TriangleRounds.Run();
//Problem12_ChocolateDivision.Run();
//Problem13_SimpleInterest.Run();
//Problem14_PoundsToKilograms.Run();
